// Notification 

export const GET_NOTIFICATION_DATA = 'GET_NOTIFICATION_DATA';
export const SET_NOTIFICATION_DATA = 'SET_NOTIFICATION_DATA';

// delete account

export const GET_DELETE_ACCOUNT_DATA = 'GET_DELETE_ACCOUNT_DATA';
export const SET_DELETE_ACCOUNT_DATA = 'SET_DELETE_ACCOUNT_DATA';

// pooja 

export const GET_POOJA_DATA = 'GET_POOJA_DATA';
export const SET_POOJA_DATA = 'SET_POOJA_DATA';

//Setings
export const GET_SPLASH = 'GET_SPLASH';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_IS_REFRESHING = 'SET_IS_REFRESHING';
export const SET_LOCATION_DATA = 'SET_LOCATION_DATA';
export const SET_IMAGE_PICKER_VISIBLE = 'SET_IMAGE_PICKER_VISIBLE'
export const SET_IS_MORE_LOADING = 'SET_IS_MORE_LOADING'
export const SET_SUB_LOCATION_DATA = 'SET_SUB_LOCATION_DATA'

//Auth
export const ON_LOGIN = 'ON_LOGIN';
export const ON_GOOGLE_LOGIN = 'ON_GOOGLE_LOGIN';
export const ON_OTP_VERIFICATION = 'ON_OTP_VERIFICATION';
export const ON_REGISTER = 'ON_REGISTER';
export const ON_APPLY_AS_AN_ASTROLOGER = 'ON_APPLY_AS_AN_ASTROLOGER';

//Customer
export const SET_CUSTOMER_DATA = 'SET_CUSTOMER_DATA';
export const GET_CUSTOMER_DATA = 'GET_CUSTOMER_DATA';
export const ON_WALLET_RECHARGE = 'ON_WALLET_RECHARGE';
export const GET_FOLLOWING_LIST = 'GET_FOLLOWING_LIST';
export const SET_FOLLOWING_LIST = 'SET_FOLLOWING_LIST';
export const GET_WALLET_RECHARGE_OFFER_LIST = 'GET_WALLET_RECHARGE_OFFER_LIST'
export const SET_WALLET_RECHARGE_OFFER_LIST = 'SET_WALLET_RECHARGE_OFFER_LIST'

//Home
export const GET_HOME_DATA = 'GET_HOME_DATA';
export const SET_HOME_BANNER = 'SET_HOME_BANNER';
export const SET_CHAT_ASTROLOGER = 'SET_CHAT_ASTROLOGER';
export const SET_CALL_ASTROLOGER = 'SET_CALL_ASTROLOGER';
export const SET_VIDEO_CALL_ASTROLOGER = 'SET_VIDEO_CALL_ASTROLOGER'
export const SET_HOME_SIMMER = 'SET_HOME_SIMMER';
export const GET_HOME_DATA_ON_REFRESH = 'GET_HOME_DATA_ON_REFRESH';
export const GET_ASTRO_COMPANION_DATA = 'GET_ASTRO_COMPANION_DATA';
export const SET_ASTRO_COMPANION_DATA = 'SET_ASTRO_COMPANION_DATA';

//Astrologer
export const GET_ASTROLOGER_DATA = 'GET_ASTROLOGER_DATA';
export const SET_ASTROLOGER_DATA = 'SET_ASTROLOGER_DATA';
export const SET_ASTROLOGER_REVIEW_DATA = 'SET_ASTROLOGER_REVIEW_DATA';
export const GET_LIVE_ASTROLOGER_DATA = 'GET_LIVE_ASTROLOGER_DATA';
export const SET_LIVE_ASTROLOGER_DATA = 'SET_LIVE_ASTROLOGER_DATA';
export const GET_RECENT_LIVESTREAMINGS = 'GET_RECENT_LIVESTREAMINGS'
export const SET_RECENT_LIVESTREAMINGS = 'SET_RECENT_LIVESTREAMINGS'
export const ON_REFRESH_LIVE_ASTROLOGER = 'ON_REFRESH_LIVE_ASTROLOGER';
export const GET_CALL_ASTROLOGERS = 'GET_CALL_ASTROLOGERS';
export const GET_MORE_CALL_ASTROLOGERS = 'GET_MORE_CALL_ASTROLOGERS'
export const GET_MORE_CHAT_ASTROLOGERS = 'GET_MORE_CHAT_ASTROLOGERS'
export const SET_CALL_ASTROLOGERS = 'SET_CALL_ASTROLOGERS';
export const ON_REFRESH_CALL_ASTROLOGER = 'ON_REFRESH_CALL_ASTROLOGER';
export const GET_CHAT_ASTROLOGERS = 'GET_CHAT_ASTROLOGERS';
export const SET_CHAT_ASTROLOGERS = 'SET_CHAT_ASTROLOGERS';
export const ON_REFRESH_CHAT_ASTROLOGER = 'ON_REFRESH_CHAT_ASTROLOGER';
export const ON_CALL_TO_ASTROLOGER = 'ON_CALL_TO_ASTROLOGER';
export const ON_VIDEO_CALL_TO_ASTROLOGER = 'ON_VIDEO_CALL_TO_ASTROLOGER'
export const SET_ASTRO_RATING_VISIBLE = 'SET_ASTRO_RATING_VISIBLE'
export const ON_ASTRO_RATING = 'ON_ASTRO_RATING'
export const ON_FOLLOW_UNFOLLOW_ASTROLOGER = 'ON_FOLLOW_UNFOLLOW_ASTROLOGER'
export const ON_CHECK_IS_FOLLOW = 'ON_CHECK_IS_FOLLOW'
export const SET_IS_FOLLOW_ASTROLOGER = 'SET_IS_FOLLOW_ASTROLOGER'
export const GET_VIDEO_CALL_ASTROLOGERS = 'GET_VIDEO_CALL_ASTROLOGERS'
export const SET_VIDEO_CALL_ASTROLOGERS = 'SET_VIDEO_CALL_ASTROLOGERS'

//Live
export const SET_LIVE_ID = 'SET_LIVE_ID';;
export const CREATE_LIVE_PROFILE = 'CREATE_LIVE_PROFILE';
export const ADD_LIVE_LISTENER = 'ADD_LIVE_LISTENER';
export const SEND_COMMENTS = 'SEND_COMMENTS';
export const SET_COMMENTS = 'SET_COMMENTS';
export const SET_MESSAGES = 'SET_MESSAGES';
export const CLEAR_COMMENTS = 'CLEAR_COMMENTS';
export const SET_GIFT_DATA = 'SET_GIFT_DATA';
export const SET_GIFT_VISIBLE = 'SET_GIFT_VISIBLE';
export const GET_GIFT_DATA = 'GET_GIFT_DATA';
export const SEND_GIFT_TO_ASTROLOGER = 'SEND_GIFT_TO_ASTROLOGER';
export const ADD_HEART = 'ADD_HEART';
export const REMOVE_HEART = 'REMOVE_HEART';
export const SET_HEARTS = 'SET_HEARTS';
export const SET_EXIT_ALERT_VISIBLE = 'SET_EXIT_ALERT_VISIBLE';
export const SET_IS_LIVE_START = 'SET_IS_LIVE_START';
export const SET_ROOM_USER_COUNT = 'SET_ROOM_USER_COUNT';
export const SET_LIVE_CALLS_VISIBLE = 'SET_LIVE_CALLS_VISIBLE';
export const SET_WAITING_LIST_VISIBLE = 'SET_WAITING_LIST_VISIBLE';
export const ADD_IN_WAITING_LIST = 'ADD_IN_WAITING_LIST';
export const SET_WAITLIST_DATA = 'SET_WAITLIST_DATA';
export const SET_CO_HOST_REQUEST_VISIBLE = 'SET_CO_HOST_REQUEST_VISIBLE';
export const SET_IS_CO_HOST = 'SET_IS_CO_HOST';
export const SET_STREAMING_ID = 'SET_STREAMING_ID';
export const ON_GO_LIVE = 'ON_GO_LIVE';
export const SET_LAYOUT = 'SET_LAYOUT';
export const RESET_LIVE_STATE = 'RESET_LIVE_STATE';
export const SET_CO_HOST_DATA = 'SET_CO_HOST_DATA';
export const ON_END_CALLING = 'ON_END_CALLING';
export const SET_GIFTED_DATA = 'SET_GIFTED_DATA';
export const ON_CANCEL_CALL_REQUEST = 'ON_CANCEL_CALL_REQUEST'
export const SET_LIVE_ASTRO_DATA = 'SET_LIVE_ASTRO_DATA'
export const SET_LIVE_DATA = 'SET_LIVE_DATA'
export const ADD_HEART_BY_OTHERS = 'ADD_HEART_BY_OTHERS'
export const ON_STREAM_UPDATE = 'ON_STREAM_UPDATE'
export const SET_CALL_INFO_VISIBLE = 'SET_CALL_INFO_VISIBLE'
export const SET_LIVE_INVOICE_VISIBLE = 'SET_LIVE_INVOICE_VISIBLE'
export const ON_LIVE_MUTE_UNMUTE = 'ON_LIVE_MUTE_UNMUTE'
export const SET_LIVE_IS_MUTE = 'SET_LIVE_IS_MUTE'
export const ON_APP_STATE_CHANGE_IN_LIVE = 'ON_APP_STATE_CHANGE_IN_LIVE'


//Chat Call videcall
export const GET_ON_VIDEO_CALL_END = 'GET_ON_VIDEO_CALL_END';
export const SET_ON_VIDEO_CALL_END = 'SET_ON_VIDEO_CALL_END';
export const GET_ON_AUDIO_CALL_END = 'GET_ON_AUDIO_CALL_END'
export const SET_ON_AUDIO_CALL_END = 'SET_ON_AUDIO_CALL_END'

export const SET_VIDEO_INVOICE_DATA = 'SET_VIDEO_INVOICE_DATA';
export const ON_CHAT_NOW = 'ON_CHAT_NOW'
export const ON_CALL_NOW = 'ON_CALL_NOW'
export const GET_MY_LINKED_PROFILE = 'GET_MY_LINKED_PROFILE'
export const ON_CHAT_REQUEST_SEND = 'ON_CHAT_REQUEST_SEND'
export const SET_LINKED_PROFILE = 'SET_LINKED_PROFILE'
export const ON_ACCEPT_REJECT_CHAT = 'ON_ACCEPT_REJECT_CHAT'
export const SET_CHAT_TIMER_COUNTDOWN = 'SET_CHAT_TIMER_COUNTDOWN'
export const SET_CHAT_DATA = 'SET_CHAT_DATA'
export const SET_CHAT_REQUESTED_DATA = 'SET_CHAT_REQUESTED_DATA'
export const ON_INITIATE_CHAT = 'ON_INITIATE_CHAT'
export const SEND_CHAT_MESSAGE = 'SEND_CHAT_MESSAGE'
export const SAVE_CHAT_MESSAGE = 'SAVE_CHAT_MESSAGE'
export const ON_END_CHAT = 'ON_END_CHAT'
export const ON_CLOSE_CHAT = 'ON_CLOSE_CHAT'
export const ON_CHAT_IMAGE_SEND = 'ON_CHAT_IMAGE_SEND'
export const SET_CHAT_IMAGE_DATA = 'SET_CHAT_IMAGE_DATA'
export const ON_RECONNECT_CHAT = 'ON_RECONNECT_CHAT'
export const SET_CALL_INVOICE_VISIBLE = 'SET_CALL_INVOICE_VISIBLE'
export const SET_VIDEOCALL_INVOICE_VISIBLE = 'SET_VIDEOCALL_INVOICE_VISIBLE'
export const SET_CALL_INVOICE_DATA = 'SET_CALL_INVOICE_DATA'
export const SET_CHAT_INVOICE_VISIBLE = 'SET_CHAT_INVOICE_VISIBLE'
export const SET_CHAT_INVOICE_DATA = 'SET_CHAT_INVOICE_DATA'
export const SET_CHAT_CALL_DATA_SAVE = 'SET_CHAT_CALL_DATA_SAVE';
export const ON_CHAT_CALL_CHECK = 'ON_CHAT_CALL_CHECK';
export const GET_LINKED_DATA = 'GET_LINKED_DATA';
export const SET_LINKED_DATA = 'SET_LINKED_DATA';
export const SET_GENERATEID_DATA = 'SET_GENERATEID_DATA'

export const SET_CAMERA_CHAT_VISION = 'SET_CAMERA_CHAT_VISION'
export const SET_CAMERA_CHAT_HAND = 'SET_CAMERA_CHAT_HAND'

//History
export const GET_CHAT_HISTORY = 'GET_CHAT_HISTORY'
export const SET_CHAT_HISTORY = 'SET_CHAT_HISTORY'
export const GET_CALL_HISTORY = 'GET_CALL_HISTORY'
export const SET_CALL_HISTORY = 'SET_CALL_HISTORY'
export const GET_LIVE_VEDIO_CALL_HISTORY = 'GET_LIVE_VEDIO_CALL_HISTORY'
export const SET_LIVE_VEDIO_CALL_HISTORY = 'SET_LIVE_VEDIO_CALL_HISTORY'
export const GET_WALLET_HISTORY = 'GET_WALLET_HISTORY';
export const SET_WALLET_HISTORY = 'SET_WALLET_HISTORY';
export const GET_VIDEO_CALL_HISTORY = 'GET_VIDEO_CALL_HISTORY'
export const SET_VIDEO_CALL_HISTORY = 'SET_VIDEO_CALL_HISTORY'

//Kundli
export const SET_KUNDLI_PAYLOADS = 'SET_KUNDLI_PAYLOADS'
export const RESET_KUNDLI_DATA = 'RESET_KUNDLI_DATA'
export const CREATE_KUNDLI = 'CREATE_KUNDLI'
export const GET_ALL_KUNDLI = 'GET_ALL_KUNDLI'
export const SET_ALL_KUNDLI = 'SET_ALL_KUNDLI'
export const SET_ALL_MASTRER_KUNDLI = 'SET_ALL_MASTRER_KUNDLI'
export const DELETE_KUNDLI = 'DELETE_KUNDLI'
export const GET_KUNDLI_DATA = 'GET_KUNDLI_DATA'
export const SET_KUNDLI_ID = 'SET_KUNDLI_ID'
export const GET_KUNDLI_BIRTH_DETAILS = 'GET_KUNDLI_BIRTH_DETAILS'
export const SET_KUNDLI_BIRTH_DETAILS = 'SET_KUNDLI_BIRTH_DETAILS'
export const GET_KUNDLI_CHART_DATA = 'GET_KUNDLI_CHART_DATA'
export const SET_KUNDLI_CHARTS = 'SET_KUNDLI_CHARTS'
export const SET_KUNDLI_CHARTS_IMAGE = 'SET_KUNDLI_CHARTS_IMAGE'
export const GET_KUNDLI_CHARTS_IMAGE = 'SET_KUNDLI_CHARTS_IMAGE'
export const SET_KUNDLI_BASIC_DETAILS = 'SET_KUNDLI_BASIC_DETAILS'
export const SET_PLANET_DATA = 'SET_PLANET_DATA'
export const GET_PLANET_DATA = 'GET_PLANET_DATA'
export const SET_KP_PLANET_DATA = 'SET_KP_PLANET_DATA'
export const GET_KP_PLANET_DATA = 'GET_KP_PLANET_DATA'
export const SET_KP_HOUSE_CUPS_DATA = 'SET_KP_HOUSE_CUPS_DATA'
export const GET_KP_HOUSE_CUPS_DATA = 'GET_KP_HOUSE_CUPS_DATA'
export const GET_KUNDLI_MAJOR_DASHA = 'GET_KUNDLI_MAJOR_DASHA'
export const SET_KUNDLI_MAJOR_DASHA = 'SET_KUNDLI_MAJOR_DASHA'
export const GET_KUNDLI_SUB_V_DASHA = 'GET_KUNDLI_SUB_V_DASHA'
export const SET_KUNDLI_SUB_V_DASHA = 'SET_KUNDLI_SUB_V_DASHA'
export const SET_KUNDLI_DAHSA_VISIBLE = 'SET_KUNDLI_DAHSA_VISIBLE'
export const SET_KUNDLI_DASHA_PATH = 'SET_KUNDLI_DASHA_PATH'
export const GET_KUNDLI_SUB_SUB_V_DASHA = 'GET_KUNDLI_SUB_SUB_V_DASHA'
export const SET_KUNDLI_SUB_SUB_V_DASHA = 'SET_KUNDLI_SUB_SUB_V_DASHA'
export const GET_KUNDLI_SUB_SUB_SUB_V_DASHA = 'GET_KUNDLI_SUB_SUB_SUB_V_DASHA'
export const SET_KUNDLI_SUB_SUB_SUB_V_DASHA = 'SET_KUNDLI_SUB_SUB_SUB_V_DASHA'
export const GET_KUNDLI_SUB_SUB_SUB_SUB_V_DASHA = 'GET_KUNDLI_SUB_SUB_SUB_SUB_V_DASHA'
export const SET_KUNDLI_SUB_SUB_SUB_SUB_V_DASHA = 'SET_KUNDLI_SUB_SUB_SUB_SUB_V_DASHA'
export const GET_HOUSE_REPORTS = 'GET_HOUSE_REPORTS'
export const SET_HOUSE_REPORTS = 'SET_HOUSE_REPORTS'
export const GET_RASHI_REPORTS = 'GET_RASHI_REPORTS';
export const SET_RASHI_REPORTS = 'SET_RASHI_REPORTS';
export const GET_ASTAK_REPORTS = 'GET_ASTAK_REPORTS';
export const SET_ASTAK_REPORTS = 'SET_ASTAK_REPORTS';
export const GET_SARVA_REPORTS = 'GET_SARVA_REPORTS';
export const SET_SARVA_REPORTS = 'SET_SARVA_REPORTS';
export const GET_ASCEDENT_REPORTS = 'GET_ASCEDENT_REPORTS';
export const SET_ASCEDENT_REPORTS = 'SET_ASCEDENT_REPORTS';
export const GET_BASIC_PANCHANGE = 'GET_BASIC_PANCHANGE';
export const SET_BASIC_PANCHANGE = 'SET_BASIC_PANCHANGE';
export const GET_NUMERO_REPORT = 'GET_NUMERO_REPORT';
export const SET_NUMERO_REPORT = 'SET_NUMERO_REPORT';
export const GET_OPEN_NUMEROLOGY = 'GET_OPEN_NUMEROLOGY';
export const SET_OPEN_NUMEROLOGY = 'SET_OPEN_NUMEROLOGY';
export const GET_DELETE_NUMEROLOGY = 'GET_DELETE_NUMEROLOGY';
export const SET_DELETE_NUMEROLOGY = 'SET_DELETE_NUMEROLOGY';

export const GET_KUNDLI_D7_CHARTS = "GET_KUNDLI_D7_CHARTS"
export const SET_KUNDLI_D7_CHARTS = "SET_KUNDLI_D7_CHARTS"
export const GET_KUNDLI_D9_CHARTS = "GET_KUNDLI_D9_CHARTS"
export const SET_KUNDLI_D9_CHARTS = "SET_KUNDLI_D9_CHARTS"


export const GET_KUNDLI_MATCHING_REPORT_POINTS = 'GET_KUNDLI_MATCHING_REPORT_POINTS'
export const SET_KUNDLI_MATCHING_REPORT_POINTS = 'SET_KUNDLI_MATCHING_REPORT_POINTS'
export const GET_KUNDLI_MATCHING_DSHKOOT_POINTS = 'GET_KUNDLI_MATCHING_DSHKOOT_POINTS'
export const SET_KUNDLI_MATCHING_DSHKOOT_POINTS = 'SET_KUNDLI_MATCHING_DSHKOOT_POINTS'
export const GET_KUNDLI_MATCHING_CONCLUSION_POINTS = 'GET_KUNDLI_MATCHING_CONCLUSION_POINTS'
export const SET_KUNDLI_MATCHING_CONCLUSION_POINTS = 'SET_KUNDLI_MATCHING_CONCLUSION_POINTS'

//Kundli Matching
export const SET_MALE_KUNDLI_DATA = 'SET_MALE_KUNDLI_DATA'
export const SET_FEMALE_KUNDLI_DATA = 'SET_FEMALE_KUNDLI_DATA'
export const GET_KUNDLI_MATCHING_REPORT = 'GET_KUNDLI_MATCHING_REPORT'
export const GET_KUNDLI_MATCHING_ASHTAKOOT_POINTS = 'GET_KUNDLI_MATCHING_ASHTAKOOT_POINTS'
export const SET_KUNDLI_MATCHING_ASHTAKOOT_POINTS = 'SET_KUNDLI_MATCHING_ASHTAKOOT_POINTS'
export const VIEW_KUNDLI_FROM_KUNDLI_MATCHING = 'VIEW_KUNDLI_FROM_KUNDLI_MATCHING'
export const SET_KUNDLI_BASIC_DETAILS_MATCHING = 'SET_KUNDLI_BASIC_DETAILS_MATCHING'
export const GET_KUNDLI_BASIC_DETAILS_MATCHING = 'GET_KUNDLI_BASIC_DETAILS_MATCHING'
export const SET_BASIC_ASTRO_POINTS = 'SET_BASIC_ASTRO_POINTS'
export const GET_BASIC_ASTRO_POINTS = 'GET_BASIC_ASTRO_POINTS'
export const GET_ASCEDENT_MATCHING_REPORTS = "GET_ASCEDENT_MATCHING_REPORTS"
export const SET_ASCEDENT_MATCHING_REPORTS = 'SET_ASCEDENT_MATCHING_REPORTS'

//Blogs
export const GET_RELIGION_AND_SPIRITUALITY = 'GET_RELIGION_AND_SPIRITUALITY'
export const SET_RELIGION_AND_SPIRITUALITY = 'SET_RELIGION_AND_SPIRITUALITY'
export const GET_BRIHAT_HOROSCOPE = 'GET_BRIHAT_HOROSCOPE'
export const SET_BRIHAT_HOROSCOPE = 'SET_BRIHAT_HOROSCOPE'
export const GET_TUTORIALS = 'GET_TUTORIALS'
export const SET_TUTORIALS = 'SET_TUTORIALS'
export const GET_MAGAZINE_DATA = 'GET_MAGAZINE_DATA'
export const SET_MAGAZINE_DATA = 'SET_MAGAZINE_DATA'
export const GET_REMEDIES_DATA = 'GET_REMEDIES_DATA'
export const SET_REMEDIES_DATA = 'SET_REMEDIES_DATA'
export const GET_DAILY_PUNCHANG_DATA = 'GET_DAILY_PUNCHANG_DATA'
export const SET_DAILY_PUNCHANG_DATA = 'SET_DAILY_PUNCHANG_DATA'
export const GET_YELLOW_BOOK_DATA = 'GET_YELLOW_BOOK_DATA'
export const SET_YELLOW_BOOK_DATA = 'SET_YELLOW_BOOK_DATA'
export const GET_AUSPICIOUS_DATA = 'GET_AUSPICIOUS_DATA'
export const SET_AUSPICIOUS_DATA = 'SET_AUSPICIOUS_DATA'
export const GET_ASTRO_BLOGS = 'GET_ASTRO_BLOGS'
export const SET_ASTRO_BLOGS = 'SET_ASTRO_BLOGS'


//Ecommerce
export const GET_PRODUCT_CATEGORY = 'GET_PRODUCT_CATEGORY'
export const SET_PRODUCT_CATEGORY = 'SET_PRODUCT_CATEGORY'
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const SET_PRODUCTS = 'SET_PRODUCTS'
export const ADD_TO_CART = 'ADD_TO_CART'
export const GET_CART_DATA = 'GET_CART_DATA'
export const SET_CART_DATA = 'SET_CART_DATA'
export const UPDATE_CART_QUANTITY = 'UPDATE_CART_QUANTITY'
export const ORDER_CART = 'ORDER_CART'
export const GET_MALL_ORDER_DATA = 'GET_MALL_ORDER_DATA'
export const SET_MALL_ORDER_DATA = 'SET_MALL_ORDER_DATA'

//Astromall
export const GET_ASTROMALL_DATA = 'GET_ASTRO_MALL_DATA'
export const SET_ASTROMALL_POOJA_DATA = 'SET_ASTROMALL_POOJA_DATA'
export const SET_ASTROMALL_SPELL_DATA = 'SET_ASTROMALL_SPELL_DATA'
export const GET_ASTROLOGER_POOJA_DATA = 'GET_ASTROLOGER_POOJA_DATA'
export const SET_ASTROLOGER_POOJA_DATA = 'SET_ASTROLOGER_POOJA_DATA'
export const ORDER_ASTROLOGER_POOJA = 'ORDER_ASTROLOGER_POOJA'
export const GET_ASTROMALL_HISTORY = 'GET_ASTROMALL_HISTORY'
export const SET_ASTROMALL_HISTORY = 'SET_ASTROMALL_HISTORY'

//Rmove the card
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM'

export const SET_ASTROLOGER_CALL = 'SET_ASTROLOGER_CALL'


//kundli click

export const GET_LAGAN_CHART = 'GET_LAGAN_CHART'
export const SET_LAGAN_CHART = 'SET_LAGAN_CHART'

// export const GET_KUNDLI_CHART_DATA = 'GET_KUNDLI_CHART_DATA'
// export const SET_KUNDLI_CHARTS = 'SET_KUNDLI_CHARTS'

export const GET_MOON_CHART = 'GET_MOON_CHART'
export const SET_MOON_CHART = 'SET_MOON_CHART'

export const GET_PLANET_STATUS = 'GET_PLANET_STATUS'
export const SET_PLANET_STATUS = 'SET_PLANET_STATUS'

export const GET_AVAKHADA_CHAKRA = 'GET_AVAKHADA_CHAKRA'
export const SET_AVAKHADA_CHAKRA = 'SET_AVAKHADA_CHAKRA'

export const GET_GHAT_CHAKRA = 'GET_GHAT_CHAKRA'
export const SET_GHAT_CHAKRA = 'SET_GHAT_CHAKRA'

export const GET_ASTAKVARGA_DATA = 'GET_ASTAKVARGA_DATA'
export const SET_ASTAKVARGA_DATA = 'SET_ASTAKVARGA_DATA'

export const GET_SARVA_DATA = 'GET_SARVA_DATA'
export const SET_SARVA_DATA = 'SET_SARVA_DATA'

export const GET_KALSARP_YOG = 'GET_KALSARP_YOG'
export const SET_KALSARP_YOG = 'SET_KALSARP_YOG'

export const GET_KALSARP_REMIDIES = 'GET_KALSARP_REMIDIES'
export const SET_KALSARP_REMIDIES = 'SET_KALSARP_REMIDIES'

export const GET_MANGLIK_YOG = 'GET_MANGLIK_YOG'
export const SET_MANGLIK_YOG = 'SET_MANGLIK_YOG'

export const GET_MAGLIK_REMEDIES = 'GET_MAGLIK_REMEDIES'
export const SET_MAGLIK_REMEDIES = 'SET_MAGLIK_REMEDIES'

export const GET_SADESATI_REPORT = 'GET_SADESATI_REPORT'
export const SET_SADESATI_REPORT = 'SET_SADESATI_REPORT'

export const GET_SADESARI_REMEDIES = 'GET_SADESARI_REMEDIES'
export const SET_SADESARI_REMEDIES = 'SET_SADESARI_REMEDIES'

export const GET_BASIC_STONE = 'GET_BASIC_STONE'
export const SET_BASIC_STONE = 'SET_BASIC_STONE'

export const GET_HEALTH_STONE = 'GET_HEALTH_STONE'
export const SET_HEALTH_STONE = 'SET_HEALTH_STONE'

export const GET_EDUCATION_STONE = 'GET_EDUCATION_STONE'
export const SET_EDUCATION_STONE = 'SET_EDUCATION_STONE'

export const GET_DAAN_STONE = 'GET_DAAN_STONE'
export const SET_DAAN_STONE = 'SET_DAAN_STONE'

export const GET_YATRA_DATA = 'GET_YATRA_DATA'
export const SET_YATRA_DATA = 'GET_YATRA_DATA'

export const GET_MANTRA_DATA = 'GET_MANTRA_DATA'
export const SET_MANTRA_DATA = 'SET_MANTRA_DATA'

export const GET_RUDRA_DATA = 'GET_RUDRA_DATA'
export const SET_RUDRA_DATA = 'SET_RUDRA_DATA'

export const GET_VISMAHADASHA_DATA = 'GET_VISMAHADASHA_DATA'
export const SET_VISMAHADASHA_DATA = 'SET_VISMAHADASHA_DATA'

export const GET_VISANTARDASH_DATA = 'GET_VISANTARDASH_DATA'
export const SET_VISANTARDASH_DATA = 'SET_VISANTARDASH_DATA'

export const GET_VISPAYANTAR_DATA = 'GET_VISPAYANTAR_DATA'
export const SET_VISPAYANTAR_DATA = 'SET_VISPAYANTAR_DATA'

export const GET_VSISUKSHAMA_DATA = 'GET_VSISUKSHAMA_DATA'
export const SET_VSISUKSHAMA_DATA = 'SET_VSISUKSHAMA_DATA'

export const GET_PRATYANTRADASHA_DATA = 'GET_PRATYANTRADASHA_DATA'
export const SET_PRATYANTRADASHA_DATA = 'SET_PRATYANTRADASHA_DATA'
///asdtadstfgasdgasf

export const GET_ASTAK_SUN = 'GET_ASTAK_SUN'
export const SET_ASTAK_SUN = 'SET_ASTAK_SUN'

export const GET_ASTAK_MOON = 'GET_ASTAK_MOON'
export const SET_ASTAK_MOON = 'SET_ASTAK_MOON'

export const GET_ASTAK_MARS = 'GET_ASTAK_MARS'
export const SET_ASTAK_MARS = 'SET_ASTAK_MARS'

export const GET_ASTAK_MER = 'GET_ASTAK_MER'
export const SET_ASTAK_MER = 'SET_ASTAK_MER'

export const GET_ASTAK_JUP = 'GET_ASTAK_JUP'
export const SET_ASTAK_JUP = 'SET_ASTAK_JUP'

export const GET_ASTAK_VEN = 'GET_ASTAK_VEN'
export const SET_ASTAK_VEN = 'SET_ASTAK_VEN'

export const GET_ASTAK_SAT = 'GET_ASTAK_SAT'
export const SET_ASTAK_SAT = 'SET_ASTAK_SAT'

export const GET_ASTAK_ASC = 'GET_ASTAK_ASC'
export const SET_ASTAK_ASC = 'SET_ASTAK_ASC'

//click match
export const GET_GUN_DATA = 'GET_GUN_DATA'
export const SET_GUN_DATA = 'SET_GUN_DATA'

export const GET_ASTKOOT_DOSA = 'GET_ASTKOOT_DOSA'
export const SET_ASTKOOT_DOSA = 'SET_ASTKOOT_DOSA'

export const GET_MATCH_MAGLIK = 'GET_MATCH_MAGLIK'
export const SET_MATCH_MAGLIK = 'SET_MATCH_MAGLIK'

export const GET_MATCH_CONCLUSION = 'GET_MATCH_CONCLUSION'
export const SET_MATCH_CONCLUSION = 'GET_MATCH_CONCLUSION'

//panachang
export const GET_PANCHA_DATA = 'GET_PANCHA_DATA'
export const SET_PANCHA_DATA = 'SET_PANCHA_DATA'

export const GET_MUHURAT_DATA = 'GET_MUHURAT_DATA'
export const SET_MUHURAT_DATA = 'SET_MUHURAT_DATA'

export const GET_DURMUHURAT_DATA = 'GET_DURMUHURAT_DATA'
export const SET_DURMUHURAT_DATA = 'SET_DURMUHURAT_DATA'

export const GET_YOG_DATA = 'GET_YOG_DATA'
export const SET_YOG_DATA = 'SET_YOG_DATA'


//Address part
export const ON_ADDRESS_CART = 'ON_ADDRESS_CART';
export const SET_ADDRESS_CART = 'SET_ADDRESS_CART';
export const GET_ADDRESS_CART = 'GET_ADDRESS_CART';
export const SET_SELECTED_ADDRESS_CART = 'SET_SELECTED_ADDRESS_CART';

export const SET_NOTIFICATION_COUNTS = 'SET_NOTIFICATION_COUNTS'
export const UPDATE_CUSTOMER_NOTIFICATION = 'UPDATE_CUSTOMER_NOTIFICATION';


